# Generated by Django 4.2.4 on 2023-12-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='cierrecaja',
            unique_together={('fecha', 'sucursal')},
        ),
    ]
