# Generated by Django 4.2.4 on 2023-11-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name_plural': 'Sucursales'},
        ),
    ]
