# Generated by Django 4.2.4 on 2023-11-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_empleado_rut_alter_empleado_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rut',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
