# Generated by Django 4.2.4 on 2023-11-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fechaNac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
